#!/usr/bin/env python3
import RPi.GPIO as GPIO
import blinky as b
import time as t

GPIO.setmode(GPIO.BCM)
GPIO.setup(16, GPIO.IN)
GPIO.setup(21, GPIO.IN)

while True:
    if GPIO.input(16) == False:
        b.random()
    if GPIO.input(21) == False:
        b.chase()
