#!/usr/bin/env python3
import RPi.GPIO as GPIO
import blinky as b
import time as t

GPIO.setmode(GPIO.BCM)
GPIO.setup(16, GPIO.IN)

while True:
    if GPIO.input(16) == False:
        b.cylon(1)
    t.sleep(0.1)
