#!/usr/bin/env python3
import RPi.GPIO as GPIO
import blinky as b
import time as t

GPIO.setmode(GPIO.BCM)
GPIO.setup(16, GPIO.IN)
GPIO.setup(21, GPIO.IN)
GPIO.setup(25, GPIO.IN)
GPIO.setup(12, GPIO.IN)
GPIO.setup(20, GPIO.IN)

while True:
    if GPIO.input(25) == False:
        b.red()
    elif GPIO.input(12) == False:
        b.yellow()
    elif GPIO.input(16) == False:
        b.green()
    elif GPIO.input(20) == False:
        b.blue()
    elif GPIO.input(21) == False:
        b.branch()
